### ISSUE TITLE
Create regular backups

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#171]
Proposal:
- Nightly backups of the database
- Weekly backups of the media folders
  /vol/signlang and /vol/signlang2 are available for the media. Perhaps the database can better go to a disk that itself is regularly backed-up.

**Comment by Woseseltops** [comment]
@ocrasborn , maybe we can make this top priority? I just occurred to me that with a simple typo, I could erase the whole database and all backups :/ .

**Comment by Woseseltops** [comment]
Suggestion 1: backup at another Ponyland disk, like /vol/bigdata2/datasets2/
* Upside: quick and easy.
* Downside: we still lose everything in case the Huygens building explodes.

Suggestion 2: backup at an external service, like Github. We could make both the NGT and the ASL dataset separate repositories that are committed overnight.
* Upside: safe.
* Downside: our data our open to everybody, and can be easily downloaded, which might not be what we want.

You pick, @ocrasborn ;)

**Comment by ocrasborn** [comment]
I pick option 1!

**Comment by Woseseltops** [comment]
Done; it now copies both databases to /vol/bigdata2/datasets2/signbank every sunday at noon. Backups are overwritten, which means that every sunday, you lose the backup from the previous week; if something goes wrong, we can go somewhere between 0 to 7 days back. Please keep this issue open so I can check whether it works.

By the way, @ocrasborn, we can make this more sophisticated; at some other places at Ponyland, we use CometBackup, a tool that intelligently cleans up older backups. Say you make a backup 4 times a day, you can for example set it so that you keep 4 backups a day for this week, 2 backups a day for the previous week, 1 backup a day for the previous month, 1 backup a week for the last 4 months, 1 backup a month for the last 2 years, etc. You can set these numbers exactly how you want them. I can't judge whether this would be incredibly useful to your team or a huge overkill (because it takes some time to setup), or somewhere in between :).

**Comment by henrinie** [comment]
@Woseseltops Are you talking about file backups, database backups or both?

> Backups are overwritten, which means that every sunday, you lose the backup from the previous week;

Without knowing any details, this sounds extremely dangerous. If you directly overwrite the last backup, can't you end up with corrupted backups, meaning that you would not actually have any backups? If not losing data is critical, I would suggest doing this some other way.

> if something goes wrong, we can go somewhere between 0 to 7 days back.

What if you don't notice the mistake in 7 days? I would also suggest a longer period of keeping the backups.

For file backups you could use incremental backups doing a full backup once a month for example, then keep updating/incrementing on those. You can do it yourself or with some backup tool. To automate the process you could create a few scripts and add them to cronjob, run full backups once a month, increments every day, once a month remove backups older than x. Add to that a database dump every night for example.

**Comment by Woseseltops** [comment]
Thanks for thinking along, @henrinie, this is about database backups. 

Before, we only had a few manual backups, all stored together. Until recently, I assumed this was not really a problem because the differences to the original import file were small, but it's now becoming clearer and clearer to me that a lot of people have changed a lot of things, and that database problems could be a disaster; that's why I proposed to give this more importance. 

The current system is a rudimentary step that saves us from things like rm -rf * in the wrong folder, but indeed not against things like longterm corrupted databases; that's why I propose something more sophisticated :). CometBackup indeed uses incremental backups, automated tasks, etc.

**Comment by ocrasborn** [comment]
How about the following:
* A nightly backup, rather than a weekly one
* Save each backup for 14 days
* Save every Monday backup for 1 month
* Save every first day of the month backup for one year
Does that make sense?

**Comment by Woseseltops** [comment]
First, the good news: the rudimentary backup system we have works! In the backup location I see file copies from last sunday.

Furthermore, I started setting up the more sophisticated CometBackup. Both the ngt and asl databases are now saved to `/vol/archive/backups` every morning. They are then cleaned following the schema below. I tried to create something that matches your wishes @ocrasborn:

    2 weeks		%d	/7	#After 2 weeks, keep every 7 days only (7,14,21,27)
    31 days		%d	7	#After 32 days, Keep one per month only
    1 year		%m	/6	#After 1 year, every 6 months only

Note that I added that we also keep one backup for every 6 months forever. This does not waste (too much) space because the backups are incremental; only differences between backups take space. This by the way also means that it would not hurt too much to make backups more frequently (like multiple times a day).

**Comment by ocrasborn** [comment]
great!

**Comment by Woseseltops** [comment]
Just did a first check, and part 1 of the great master plan is working. I see backups every day:

    drwxrws--- 3 wstoop wwwclam   4,0K okt 28 20:21 2016-10-29 05:00
    drwxrws--- 3 wstoop wwwclam   4,0K okt 30 00:54 2016-10-30 05:00
    drwxrws--- 3 wstoop wwwclam   4,0K okt 30 11:32 2016-10-31 05:00
    drwxrws--- 3 wstoop wwwclam   4,0K okt 31 22:34 2016-11-01 05:00
    drwxrws--- 3 wstoop wwwclam   4,0K nov  2 04:52 2016-11-02 05:00
    drwxrws--- 3 wstoop wwwclam   4,0K nov  2 04:52 current

In a week or two we will see whether the cleaning schedule also work, so please keep this issue open a bit longer :)

**Comment by Woseseltops** [comment]
Update, the current contents of the backup directory:

    drwxrwsr-x 17 wstoop clstadmin   4,0K nov 18 05:30 .
    drwxrwsr-x  7  12193 clstadmin   4,0K okt 29 05:30 ..
    drwxrws---  3 wstoop wwwsignbank 4,0K nov  5 03:43 2016-11-05 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov  6 03:59 2016-11-06 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov  7 03:43 2016-11-07 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov  8 03:44 2016-11-08 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov  9 04:03 2016-11-09 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 10 04:00 2016-11-10 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 11 03:44 2016-11-11 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 12 03:43 2016-11-12 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 13 03:44 2016-11-13 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 14 03:52 2016-11-14 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 15 03:53 2016-11-15 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 16 03:55 2016-11-16 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 17 03:49 2016-11-17 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 18 03:56 2016-11-18 05:00
    drwxrws---  3 wstoop wwwsignbank 4,0K nov 18 03:56 current

So far, nothing has been stored older than 2 weeks. I think this is because cometbackup will only keep the days with numbers 7, 14, 21 and 27, and all backups cleaned up so far did not have any of these numbers. If my hypothesis is correct, the backup '03:43 2016-11-07 05:00' should be kept next week while the others are gone.

Note: the whole thing is still running on my account. Once we verify it works, we transfer it to Onno's acount.

**Comment by Woseseltops** [comment]
Hypothesis confirmed! I love it when that happens :).

I've now moved it to the account of @ocrasborn , let's see if keeps working.

**Comment by Woseseltops** [comment]
It didn't initially (permission problem), but when I fixed that I see backups are being created again. @ocrasborn  reports these logs:

    Creating differential backup /scratch2/www/ASL-signbank/writable/database/ --> /vol/archive/backups/asl-signbank/current
     rsync -avzW --delete "/scratch2/www/ASL-signbank/writable/database//" "/vol/archive/backups/asl-signbank/current"
    sending incremental file list
    rsync: failed to set times on "/vol/archive/backups/asl-signbank/current/.": Operation not permitted (1)
    ./
    signbank.db

    sent 3,953,227 bytes  received 148 bytes  1,581,350.00 bytes/sec
    total size is 220,657,664  speedup is 55.82
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183)     [sender=3.1.0]
    Creating archive copy current --> 2016-11-25 05:00
     cp -lar "/vol/archive/backups/asl-signbank/current" "/vol/archive/backups/asl-signbank/2016-11-25     05:00"
    Cleaning up backup directory.

    2016-11-07 05:00 !
    2016-11-10 05:00 deleting
    2016-11-11 05:00 deleting
    2016-11-12 05:00 
    2016-11-13 05:00 
    2016-11-14 05:00 !
    2016-11-15 05:00 
    2016-11-16 05:00 
    2016-11-17 05:00 
    2016-11-18 05:00 
    2016-11-19 05:00 
    2016-11-20 05:00 
    2016-11-21 05:00 !
    2016-11-22 05:00 
    2016-11-23 05:00 
    2016-11-25 05:00 
    Done.

It looked it up, and this is only a problem with setting modification times, so not really a problem for content. It works! And it think it's very likely that the error will be away tomorrow as well; let me know, @ocrasborn !

**Comment by ocrasborn** [comment]
Nope, error still here (Nov 27):
Creating differential backup /scratch2/www/ASL-signbank/writable/database/ --> /vol/archive/backups/asl-signbank/current
 rsync -avzW --delete "/scratch2/www/ASL-signbank/writable/database//" "/vol/archive/backups/asl-signbank/current"
sending incremental file list
rsync: failed to set times on "/vol/archive/backups/asl-signbank/current/.": Operation not permitted (1)
./
signbank.db

**Comment by Woseseltops** [comment]
Too bad. I might a slight change to the backup configuration, so that it no longer tries to copy times. Let me know if it works, @ocrasborn .

**Comment by ocrasborn** [comment]
Works, @Woseseltops !
