### ISSUE TITLE
Create a local/working copy of the Corpus NGT SVN repo in a place where Signbank can read and write

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#69]
@aarsom will provide the source actual location of the file
@ocrasborn what is the goal location of the file?

**Comment by ocrasborn** [comment]
@Woseseltops: They should be in a location that can only be read by the system, not by users. What would be a good place for that?
Related: at some point it would be useful to run nightly maintenance scripts on a recent update of a SVN checkout that can then be committed back automatically. Can we join these two wishes? (Now, the checkout/update is just for extracting frequencies, not committing anything back in.) [@richardbank]

**Comment by Woseseltops** [comment]
I think this escaped @aarsom's attention, I emailed her a reminder. 

>  Can we join these two wishes?

More or less yes, as I would use the same tool (Crontab) to do it. If it's only a script that needs to be executed nightly, it's only a Crontab oneliner. If the commit is not part of the script, would need an extra line for that :).

**Comment by ocrasborn** [comment]
...and add a routine that updates the working copy every night.
--> This working copy will form the basis for:
1.  updating the corpus on the basis of the ECV file that Signbank.
2. refreshing the corpus statistics (token frequencies) in Signbank

**Comment by Woseseltops** [comment]
Aha, so instead of taking a file out of the repo, we now copy the whole repo.

I added a cronjob on my Ponyland account on Applejack that copies the folder /scratch2/svnrepos/signlang/corpus-ngt/ to /www/signbank/live/writable/corpus-ngt-repo every five minutes .

Once I verify that everything works correctly, two things need to be changed:
* Change from 5 minutes to once a day, to save the energy.
* Transfer the job to one of your Ponyland accounts, so that this will continue if I ever change jobs and my account is deleted (not that I'm planning anything :) ).

**Comment by ocrasborn** [comment]
As I understood it from Aarthy, the .eaf files in the subdir /eaf of the repo are not directly readable, they are in some sort of SVN database, and need to be checked out first (svnadmin checkout?), after which they can be updated by the cronjob (and changed - committed back in the case of changes from Signbank to the EAFs). No?

**Comment by richardbank** [comment]
I was about to write the same thing :-)
I think we need to install an SVN-client on the server which (once) checks out a working copy and (recurrently) commits any changes made by Signbank into the repo.

**Comment by Woseseltops** [comment]
Aha, so a misunderstanding. You don't want to copy the bare repository, you want a checkout. I'll undo the thing I described above and look into svn checkouts from the command line.

**Comment by Woseseltops** [comment]
Note to self, this works: 

    svn checkout svn+ssh://wstoop@applejack.science.ru.nl/scratch2/svnrepos/signlang/corpus-ngt/ corpus-ngt

**Comment by ocrasborn** [comment]
From within the repo, we really only want the subdir /eaf. That's where the annotation files are, in subdirectories per 100 files named CNGT0000-CNGT0099, CNGT0100-CNGT0199, etc. The other directories are for metadata (/imdi, .imdi files), manuals etc. (/Administratie), and several subdirs for preference files that come with the eaf files but that we won't need to read from or write to.

**Comment by Woseseltops** [comment]
A fresh checkout of the svn server is now created in the Signbank writable folder, every morning at 02:00h. I think that makes this issue finished; let's continue with #55.

**Comment by Woseseltops** [comment]
I moved this to Onno's account, but Onno now reports this error: 

> On 19 Dec 2015, at 02:00, Cron Daemon <root@science.ru.nl> wrote:
> 
> rm: cannot remove ‘/www/signbank/live/writable/corpus-ngt-repo/’: No such file or directory
> no matching hostkey found
> svn: E210002: Unable to connect to a repository at URL 'svn+ssh://wstoop@applejack.science.ru.nl/scratch2/svnrepos/signlang/corpus-ngt'
> svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file.
> svn: E210002: Network connection closed unexpectedly

@ocrasborn , could you reopen this issue?

**Comment by Woseseltops** [comment]
Ah, stupid, of course your account cannot log into Ponyland as my account. I now changed it to svn+ssh://ocrasborn@applejack.science.ru.nl, and now it seems to work. Please leave this issue open so I don't forget to check next week.

**Comment by ocrasborn** [comment]
The log mail I get indicates it works OK; I pasted the first lines and the last one below. One remaining issue though: it doesn't put things in the subdir /writable/, but /writ$/ -- typo?

----------
A    /www/signbank/live/writ$/corpus-ngt
A    /www/signbank/live/writ$/corpus-ngt/Administratie
A    /www/signbank/live/writ$/corpus-ngt/Administratie/CNGT_r2_ReleaseNotes.docx
A    /www/signbank/live/writ$/corpus-ngt/Administratie/Stappenplan_annotatie.docx
A    /www/signbank/live/writ$/corpus-ngt/Administratie/CNGT_r3_ReleaseNotes.docx
[...]
Checked out revision 26217.
----------

**Comment by ocrasborn** [comment]
Oh, and another thing: can you have the log info be written to a (weekly rotating?) file, rather than a daily email message?

**Comment by ocrasborn** [comment]
@Woseseltops : here's this mornings log message:
------------
rm: cannot remove ‘/www/signbank/live/writable/corpus-ngt-repo/’: No such file or directory
Checked out revision 26217.
------------
Rather than removing the repo and checking out a fresh one, why not use 'svn update'? Is there a reason for that? (And see above: the rm didn't work because it's not in /writable but in /writ$, I presume, see comment above

**Comment by Woseseltops** [comment]
> it doesn't put things in the subdir /writable/, but /writ$/ -- typo?

Yes, looks like something went wrong with copying from the command line. 

> can you have the log info be written to a (weekly rotating?) file

Done. The mail thing is crontab default behavior; I've now changed it so it writes output to a file in /scratch/signbank-logs/ .

> rm: cannot remove ‘/www/signbank/live/writable/corpus-ngt-repo/’

Ah yeah, that's because of the typo. It's trying to remove something at the correct location that was created at the wrong location.

> Rather than removing the repo and checking out a fresh one, why not use 'svn update'? 

I feel a bit like this guy now:

![](http://www.northernstarfitness.co.uk/uploads/3/4/4/5/3445158/2919501_orig.jpg)

I've improved it now, let's see if it works.

**Comment by ocrasborn** [comment]
:-)

**Comment by ocrasborn** [comment]
I still get email logs. This morning's one said this:

/bin/sh: 1: Syntax error: EOF in backquote substitution

**Comment by Woseseltops** [comment]
I looked it up, and it turns out that cron cannot handle the % sign, which was in the part that creates the daily log file... and of course it emailed you about it because it didn't know what to do with the error. I've fixed it now, let's see what the next problem will be.

PS
It is normal that it takes a lot of time to get a cronjob right ;).

**Comment by Woseseltops** [comment]
It still does not fully work; it creates the logfiles, but it does not write to do them. I've slightly altered the commands now.

**Comment by Woseseltops** [comment]
I now see log files with expected content. It works?

**Comment by ocrasborn** [comment]
Yes!
